import { PatchFlags, SlotFlags, isSymbol } from '@arrange/vue-shared'
import { isAsyncWrapper } from '../apiAsyncComponent.ts'
import type { Data } from '../component.ts'
import {
    type ContextualRenderFn,
    currentRenderingInstance,
} from '../componentRenderContext.ts'
import type { RawSlots, Slots } from '../componentSlots.ts'
import { isValueExpression } from '../valueBinding.ts'
import {
    Comment,
    Fragment,
    type VNode,
    type VNodeArrayChildren,
    createBlock,
    createVNode,
    isVNode,
    openBlock,
} from '../vnode.ts'
import { warn } from '../warning.ts'

/**
 * Compiler runtime helper for rendering `<slot/>`
 * @private
 */
export function renderSlot(
    slots: Slots,
    name: string,
    props: Data = {},
    // this is not a user-facing function, so the fallback is always generated by
    // the compiler and guaranteed to be a function returning an array
    fallback?: () => VNodeArrayChildren,
): VNode {

    let slot = slots[name]

    // a compiled slot disables block tracking by default to avoid manual
    // invocation interfering with template-based block tracking, but in
    // `renderSlot` we can be sure that it's template-based so we can force
    // enable it.
    if (slot && (slot as ContextualRenderFn)._c) {
        ; (slot as ContextualRenderFn)._d = false
    }
    openBlock()
    const slotProps = Object.defineProperties({}, Object.fromEntries(Object.keys(props).map(key => [key, {
        enumerable: true,
        get: () => isValueExpression(props[key]) ? props[key].read() : props[key],
    }])))
    const validSlotContent = slot && ensureValidVNode(slot(slotProps))
    const slotKey =
        props.key ||
        // slot content array of a dynamic conditional slot may have a branch
        // key attached in the `createSlots` helper, respect that
        (validSlotContent && (validSlotContent as any).key)
    const rendered = createBlock(
        Fragment,
        {
            key:
                (slotKey && !isSymbol(slotKey) ? slotKey : `_${name}`) +
                // #7256 force differentiate fallback content from actual content
                (!validSlotContent && fallback ? '_fb' : ''),
        },
        validSlotContent || (fallback ? fallback() : []),
        validSlotContent && (slots as RawSlots)._ === SlotFlags.STABLE
            ? PatchFlags.STABLE_FRAGMENT
            : PatchFlags.BAIL,
    )
    if (slot && (slot as ContextualRenderFn)._c) {
        ; (slot as ContextualRenderFn)._d = true
    }
    return rendered
}

export function ensureValidVNode(
    vnodes: VNodeArrayChildren,
): VNodeArrayChildren | null {
    return vnodes.some(child => {
        if (!isVNode(child)) return true
        if (child.type === Comment) return false
        if (
            child.type === Fragment &&
            !ensureValidVNode(child.children as VNodeArrayChildren)
        )
            return false
        return true
    })
        ? vnodes
        : null
}
