export enum ShapeFlags {
    LAYOUT_INVOCATION = 1,
    FUNCTIONAL_ARRANGABLE = 1 << 1,
    STATEFUL_ARRANGABLE = 1 << 2,
    ARRAY_CHILDREN = 1 << 4,
    SLOTS_CHILDREN = 1 << 5,
    ARRANGABLE = ShapeFlags.STATEFUL_ARRANGABLE | ShapeFlags.FUNCTIONAL_ARRANGABLE,
}
