export * from '@arrange/vue-reactivity'
export { computed } from './apiComputed.ts'
export { defineArrangable } from './apiDefineArrangable.ts'
export type { DefineArrangable } from './apiDefineArrangable.ts'
export type { Arrangable, ArrangableDefinition, ArrangableProps, SetupContext, StructureProgram, Content, Contents, AppConfig } from './arrangable.ts'
export type { PropType, ExtractPropTypes, ExtractPublicPropTypes, PropInputs } from './arrangableProps.ts'
export { provide, inject, hasInjectionContext } from './apiInject.ts'
export type { InjectionKey } from './apiInject.ts'
export * from './apiLifecycle.ts'
export { watch, watchEffect, watchPostEffect, watchSyncEffect } from './apiWatch.ts'
export type { WatchOptions, WatchHandle, WatchSource } from './apiWatch.ts'
export { defineProps, withDefaults, mergeDefaults, createPropsRestProxy, useSlots } from './apiSetupHelpers.ts'
export { nextTick } from './scheduler.ts'
export { useId } from './helpers/useId.ts'
export { getArrangeExecutionStats } from './executionStats.ts'

// 编译产物使用的统一结构协议，包入口整理阶段再集中到内部子路径
export { callArrangable, arrangeScope, invokeContent, retainContent, arrangeList, parameterInputs, parameterObject } from './rearrange.ts'
export { prepareParameters } from './propDeclarations.ts'
export { resolveArrangable, resolveDynamicArrangable } from './helpers/resolveAssets.ts'
export { arrangeParameterName, camelize, capitalize } from '@arrange/vue-shared'
