include_guard(GLOBAL)

# JUCE 8.0.12 的 VST3 命令转义和 UTF-16 class info 存在缺陷
# 仅在构建树修正已知定义，不修改依赖检出或复制整套 JUCE 目标逻辑
function(arrange_fix_juce_vst3_commands)
    file(READ "${JUCE_CMAKE_UTILS_DIR}/JUCEUtils.cmake" _arrange_juce_utils)
    string(REPLACE "\r\n" "\n" _arrange_juce_utils "${_arrange_juce_utils}")

    get_target_property(_arrange_module_directory juce::juce_audio_plugin_client INTERFACE_JUCE_MODULE_PATH)
    set(_arrange_vst3_source "${_arrange_module_directory}/juce_audio_plugin_client/VST3")
    set(_arrange_overlay "${CMAKE_CURRENT_BINARY_DIR}/juce-vst3-compat")
    set(_arrange_overlay_vst3 "${_arrange_overlay}/juce_audio_plugin_client/VST3")
    file(READ "${_arrange_vst3_source}/juce_VST3ModuleInfo.h" _arrange_module_info)
    set(_arrange_unicode_before "infoW.fromAscii (info2);")
    set(_arrange_unicode_after [=[infoW = Steinberg::PClassInfoW (info2.cid,
                                          info2.cardinality,
                                          info2.category,
                                          reinterpret_cast<const Steinberg::char16*> (u"" JucePlugin_Name),
                                          info2.classFlags,
                                          info2.subCategories,
                                          reinterpret_cast<const Steinberg::char16*> (u"" JucePlugin_Manufacturer),
                                          reinterpret_cast<const Steinberg::char16*> (u"" JucePlugin_VersionString),
                                          reinterpret_cast<const Steinberg::char16*> (u"" kVstVersionString));]=])
    string(FIND "${_arrange_module_info}" "${_arrange_unicode_before}" _arrange_unicode_match)
    if(_arrange_unicode_match LESS 0)
        message(FATAL_ERROR "JUCE VST3 Unicode 名称定义与 Arrange 兼容修正不符，请审查 JUCE 版本")
    endif()
    string(REPLACE "${_arrange_unicode_before}" "${_arrange_unicode_after}" _arrange_module_info "${_arrange_module_info}")
    file(CONFIGURE OUTPUT "${_arrange_overlay_vst3}/juce_VST3ModuleInfo.h" CONTENT "${_arrange_module_info}" @ONLY)
    target_include_directories(juce_audio_plugin_client BEFORE INTERFACE "${_arrange_overlay}")
    file(READ "${_arrange_vst3_source}/juce_VST3ManifestHelper.cpp" _arrange_helper_source)
    set(_arrange_sdk_module_directory "${_arrange_module_directory}/juce_audio_processors_headless/format_types/VST3_SDK/public.sdk/source/vst/hosting")
    file(READ "${_arrange_sdk_module_directory}/module.cpp" _arrange_host_module)
    string(FIND "${_arrange_host_module}" "ClassInfo::ClassInfo (const PClassInfoW& info) noexcept" _arrange_unicode_start)
    if(_arrange_unicode_start LESS 0)
        message(FATAL_ERROR "VST3 SDK Unicode class info 定义与 Arrange 兼容修正不符")
    endif()
    string(SUBSTRING "${_arrange_host_module}" ${_arrange_unicode_start} -1 _arrange_unicode_remaining)
    string(FIND "${_arrange_unicode_remaining}" "\n}" _arrange_unicode_end)
    if(_arrange_unicode_end LESS 0)
        message(FATAL_ERROR "VST3 SDK Unicode class info 定义未闭合")
    endif()
    math(EXPR _arrange_unicode_length "${_arrange_unicode_end} + 2")
    string(SUBSTRING "${_arrange_unicode_remaining}" 0 ${_arrange_unicode_length} _arrange_unicode_definition)
    set(_arrange_unicode_original "${_arrange_unicode_definition}")
    foreach(_arrange_field IN ITEMS name vendor version sdkVersion)
        string(REGEX REPLACE "StringConvert::convert \\(info\\.${_arrange_field}, [^)]+\\)" "StringConvert::convert (std::u16string (reinterpret_cast<const char16_t*> (info.${_arrange_field})))" _arrange_unicode_definition "${_arrange_unicode_definition}")
        string(FIND "${_arrange_unicode_definition}" "StringConvert::convert (info.${_arrange_field}," _arrange_field_match)
        if(NOT _arrange_field_match LESS 0)
            message(FATAL_ERROR "VST3 SDK 字段未能应用 UTF-16 兼容修正：${_arrange_field}")
        endif()
    endforeach()
    if(_arrange_unicode_definition STREQUAL _arrange_unicode_original)
        message(FATAL_ERROR "VST3 SDK UTF-16 转换定义与 Arrange 兼容修正不符")
    endif()
    string(REPLACE "${_arrange_unicode_original}" "${_arrange_unicode_definition}" _arrange_host_module "${_arrange_host_module}")
    set(_arrange_helper_module_include [=[#include <juce_audio_processors_headless/format_types/VST3_SDK/public.sdk/source/vst/hosting/module.cpp>]=])
    set(_arrange_helper_overlay_include [=[#include "@ARRANGE_VST3_OVERLAY@/module.cpp"]=])
    set(ARRANGE_VST3_OVERLAY "${_arrange_overlay}")
    string(CONFIGURE "${_arrange_helper_overlay_include}" _arrange_helper_overlay_include @ONLY)
    string(FIND "${_arrange_helper_source}" "${_arrange_helper_module_include}" _arrange_module_include_match)
    if(_arrange_module_include_match LESS 0)
        message(FATAL_ERROR "JUCE VST3 manifest helper 的 module.cpp include 与兼容修正不符")
    endif()
    string(FIND "${_arrange_helper_source}" [=[#include "juce_VST3ModuleInfo.h"]=] _arrange_info_include_match)
    if(_arrange_info_include_match LESS 0)
        message(FATAL_ERROR "JUCE VST3 manifest helper 的 module info include 与兼容修正不符")
    endif()
    string(FIND "${_arrange_host_module}" [=[#include "module.h"]=] _arrange_module_header_match)
    if(_arrange_module_header_match LESS 0)
        message(FATAL_ERROR "VST3 SDK module.cpp 的 module.h include 与兼容修正不符")
    endif()
    set(_arrange_module_header_include "#include \"${_arrange_sdk_module_directory}/module.h\"")
    string(REPLACE [=[#include "module.h"]=] "${_arrange_module_header_include}" _arrange_host_module "${_arrange_host_module}")
    file(CONFIGURE OUTPUT "${_arrange_overlay}/module.cpp" CONTENT "${_arrange_host_module}" @ONLY)
    string(REPLACE "${_arrange_helper_module_include}" "${_arrange_helper_overlay_include}" _arrange_helper_source "${_arrange_helper_source}")
    string(REPLACE [=[#include "juce_VST3ModuleInfo.h"]=] [=[#include <juce_audio_plugin_client/VST3/juce_VST3ModuleInfo.h>]=] _arrange_helper_source "${_arrange_helper_source}")
    file(CONFIGURE OUTPUT "${_arrange_overlay_vst3}/juce_VST3ManifestHelper.cpp" CONTENT "${_arrange_helper_source}" @ONLY)
    file(CONFIGURE OUTPUT "${_arrange_overlay_vst3}/juce_VST3ManifestHelper.mm" CONTENT "#include \"juce_VST3ManifestHelper.cpp\"\n" @ONLY)

    set(_arrange_remove_before [=["${output_path}/Contents/Resources/moduleinfo.json")]=])
    set(_arrange_remove_after [=["${output_path}/Contents/Resources/moduleinfo.json" VERBATIM)]=])
    set(_arrange_manifest_before [=[    add_custom_command(TARGET ${target_name} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E echo "creating ${output_path}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${product}/Contents/Resources"
        COMMAND ${shared_code_target}_vst3_helper > "${ouput_path}")]=])
    set(_arrange_manifest_after [=[    add_custom_command(TARGET ${target_name} POST_BUILD
        COMMAND "${CMAKE_COMMAND}" "-DARRANGE_VST3_HELPER=$<TARGET_FILE:${shared_code_target}_vst3_helper>" "-DARRANGE_VST3_MANIFEST=${ouput_path}" -P "@ARRANGE_VST3_MANIFEST_SCRIPT@"
        VERBATIM)]=])
    set(ARRANGE_VST3_MANIFEST_SCRIPT "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/WriteVst3Manifest.cmake")
    string(CONFIGURE "${_arrange_manifest_after}" _arrange_manifest_after @ONLY)

    set(_arrange_helper_before [=[add_executable(${vst3_helper_target} "${source}")]=])
    set(_arrange_helper_after [=[add_executable(${vst3_helper_target} "@ARRANGE_VST3_HELPER_DIRECTORY@/juce_VST3ManifestHelper.${extension}")
    target_include_directories(${vst3_helper_target} BEFORE PRIVATE "@ARRANGE_VST3_OVERLAY@")]=])
    set(ARRANGE_VST3_HELPER_DIRECTORY "${_arrange_overlay_vst3}")
    set(ARRANGE_VST3_OVERLAY "${_arrange_overlay}")
    string(CONFIGURE "${_arrange_helper_after}" _arrange_helper_after @ONLY)

    foreach(_arrange_function IN ITEMS _juce_set_plugin_target_properties juce_enable_vst3_manifest_step _juce_add_vst3_manifest_helper_target)
        string(FIND "${_arrange_juce_utils}" "function(${_arrange_function} " _arrange_start)
        if(_arrange_start LESS 0)
            message(FATAL_ERROR "无法定位 JUCE VST3 构建定义：${_arrange_function}")
        endif()
        string(SUBSTRING "${_arrange_juce_utils}" ${_arrange_start} -1 _arrange_remaining)
        string(FIND "${_arrange_remaining}" "endfunction()" _arrange_end)
        if(_arrange_end LESS 0)
            message(FATAL_ERROR "JUCE VST3 构建定义未闭合：${_arrange_function}")
        endif()
        string(LENGTH "endfunction()" _arrange_end_length)
        math(EXPR _arrange_length "${_arrange_end} + ${_arrange_end_length}")
        string(SUBSTRING "${_arrange_remaining}" 0 ${_arrange_length} _arrange_definition)
        if(_arrange_function STREQUAL "_juce_set_plugin_target_properties")
            set(_arrange_before "${_arrange_remove_before}")
            set(_arrange_after "${_arrange_remove_after}")
        elseif(_arrange_function STREQUAL "juce_enable_vst3_manifest_step")
            set(_arrange_before "${_arrange_manifest_before}")
            set(_arrange_after "${_arrange_manifest_after}")
        else()
            set(_arrange_before "${_arrange_helper_before}")
            set(_arrange_after "${_arrange_helper_after}")
        endif()
        string(FIND "${_arrange_definition}" "${_arrange_before}" _arrange_match)
        if(_arrange_match LESS 0)
            message(FATAL_ERROR "JUCE VST3 命令定义与 Arrange 兼容修正不符；请审查 JUCE 版本和构建命令：${_arrange_function}")
        endif()
        string(REPLACE "${_arrange_before}" "${_arrange_after}" _arrange_definition "${_arrange_definition}")
        cmake_language(EVAL CODE "${_arrange_definition}")
    endforeach()
endfunction()

arrange_fix_juce_vst3_commands()
